// Types for the Emscripten glue generated by build/build.sh (src/wasm/qpdf.mjs).
export interface QpdfFS {
  writeFile(path: string, data: Uint8Array | string): void;
  /** A fresh copy (not a view of the wasm heap), so it owns a plain ArrayBuffer. */
  readFile(path: string): Uint8Array<ArrayBuffer>;
  readdir(path: string): string[];
  mkdir(path: string): void;
  chdir(path: string): void;
  stat(path: string): { mode: number; size: number };
  isDir(mode: number): boolean;
  isFile(mode: number): boolean;
  analyzePath(path: string): { exists: boolean };
}

export interface QpdfModule {
  FS: QpdfFS;
  /** Returns the exit code, or throws an ExitStatus-like `{ status }` when qpdf calls exit(). */
  callMain(args: string[]): number | undefined;
}

export interface QpdfModuleOptions {
  thisProgram?: string;
  print?: (line: string) => void;
  printErr?: (line: string) => void;
  instantiateWasm?: (
    imports: WebAssembly.Imports,
    ready: (instance: WebAssembly.Instance, module: WebAssembly.Module) => void,
  ) => object;
}

export default function createQpdfModule(options?: QpdfModuleOptions): Promise<QpdfModule>;
